name: pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  year-process:
    runs-on: ubuntu-latest
    steps:    
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Update README.md
        run: |
          node index.js > README.md
      - name: Commit change & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "bot: update README.md" || echo "No changes to commit"
          git push
